### ISSUE TITLE
I can't find my inspiration </3 XD 

### ISSUE THREAD

**Issue by axetrodome** [four-eyes-04-04/super-quotes#4]
![image](https://user-images.githubusercontent.com/25072187/27771822-ab40ec38-5f88-11e7-94f1-47e6b7502447.png)

**Comment by aprilmintacpineda** [comment]
nakita ko na boss kung anong problema sayo, pwede mo bang i-screenshot yung result ng `php --version` mo para makita ko kung anong _php version_ gamit mo?

**Comment by aprilmintacpineda** [comment]
Try mo ulit boss, na-fixed ko na.
